### ISSUE TITLE
Screen is zoomed in when opening (SteamOS)

### ISSUE THREAD

**Issue by JAWITOR** [ScanMountGoat/ultimate_tex#10]
I recently downloaded Ultimate_tex but i’m having an issue where the screen will zoom in where yiu can barely see anything

**Comment by ScanMountGoat** [comment]
Do you have a screenshot? What operating system are you using?

**Comment by JAWITOR** [comment]
I’m using steam OS

**Comment by ScanMountGoat** [comment]
This will be harder for me to reproduce since I don't have any devices running steamos. This may be fixed in a future release if I finish the UI rewrite. There are a lot of scaling issues on different platforms that can be hard to track down.

**Comment by JAWITOR** [comment]
Yeah, I was able to get it to work by going into gaming mode on my steam deck

**Comment by ScanMountGoat** [comment]
Closing this as the latest version uses a completely different method for drawing the UI.
