### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by TurtleJoe69** [ScanMountGoat/ultimate_tex#11]
Every time I import my batch of BNTX files, and set the output folder, everything works perfectly. But as soon as I click export, the program crashes with no explanation or error. I have the Microsoft thing already so I really can’t tell what’s wrong. Any tips would be greatly appreciated.

**Comment by ScanMountGoat** [comment]
Are you able to convert other file types from different folders or does this just happen with bntx? What operating system are you using?

**Comment by TurtleJoe69** [comment]
No I’m not able to convert anything at all actually. I’m using windows and I made sure to download the correct file for it

**Comment by ScanMountGoat** [comment]
What CPU do you have in your computer? There may be a compatibility issue from older hardware. I would try converting to DDS or PNG. DDS should work if you're able to at least open the application.

**Comment by ScanMountGoat** [comment]
If you're still experiencing this on the latest version, please make a new issue as the application has changed significantly.
