### ISSUE TITLE
Setting mipmaps override locks exporting again

### ISSUE THREAD

**Issue by SpaceMacce** [ScanMountGoat/ultimate_tex#12]
0.2.0 will not export multiple files at
 the same time. 
![Screenshot 2023-08-26 080352](https://github.com/ScanMountGoat/ultimate_tex/assets/83364216/8f2941c3-98ec-4ee0-bad3-6c960daf6fbe)
I went back to 0.1.3 to export them no problem.

**Comment by ScanMountGoat** [comment]
You can still export multiple files at a time in the same export operation. The export button will be enabled again when the export operation finishes. There's a bug when overriding the mipmaps setting that causes the button to get stuck. Set mipmaps to "Custom..." for now, which should still enable mipmaps. I'll try and get a new release out later tonight with a fix.
