### ISSUE TITLE
162x162 images won't convert back to .bntx

### ISSUE THREAD

**Issue by shawnm07** [ScanMountGoat/ultimate_tex#13]
everytime I try and no matter what I do, for some reason just 162x162 images dont convert back into .bntx

**Comment by ScanMountGoat** [comment]
What type of files are the inputs? Does it work when saving as another type of file like nutexb?

**Comment by shawnm07** [comment]
Yah it only doesn’t work with bntx. I’m using pngs that were bntx and then converted.

**Comment by ScanMountGoat** [comment]
There's currently a bug setting the output format manually. I'll try and get a fixed release out later today. As a workaround, you can set the format to  "Color (sRGB) + Alpha" or "Color (Linear) + Alpha" or use the previous release.

**Comment by shawnm07** [comment]
Ok thank you so much!
