### ISSUE TITLE
Error converting chara_4_eflame_only_01.png 162x162 to bntx

### ISSUE THREAD

**Issue by shawnm07** [ScanMountGoat/ultimate_tex#17]
hey sorry if Im not supposed to start a new issue. I wasn't sure since you closed the last one but now the newest release it unfortunately still doesnt work but shows an error message this time. 

Error converting chara_4_eflame_only_01.png: error compressing surface: surface dimensions 162 x 162 x 1 are not divisibly by the block dimensions 4 x 4

Is this something thats fixable?

**Comment by ScanMountGoat** [comment]
This is fixable, but the changes will be more involved on my end. I don't have any estimate on when I'll release 0.2.3 for Ultimate Tex. 

You can technically still use 162x162 textures on the current version as long as you use DDS as the input. It's only the conversions from uncompressed formats like  png or jpeg to formats like dds, bntx, or nutexb that assume the input dimensions are divisible. If you're on windows, the easiest for now is to just use something like paint.net or photoshop to export your edits as dds and use Ultimate Tex to convert to bntx.

**Comment by shawnm07** [comment]
unfortunately dds came with the same problem no matter what I tried. Are there any other options?

**Comment by ScanMountGoat** [comment]
It should work as long as the output image format matches the input image format for the dds file. Ultimate Tex can detect this case and avoid doing any conversions. You'll want to save the file as BC7Srgb or BC7Unorm in an image editor depending on how you want to handle gamma and use Ultimate Tex to convert that dds to bntx.

**Comment by shawnm07** [comment]
unfortunately thats not working either.

**Comment by ScanMountGoat** [comment]
It definitely works as long as the format doesn't change. Here's the settings I'm using.
![image](https://github.com/ScanMountGoat/ultimate_tex/assets/23301691/bfb98d26-d8eb-4679-b173-9c4439f6ebf9)
