### ISSUE TITLE
won't boot up

### ISSUE THREAD

**Issue by KuyaWasTaken** [ScanMountGoat/ultimate_tex#7]
it just stays white and i cannot use it. I installed all I need too. I have windows

**Comment by ScanMountGoat** [comment]
What GPU do you have or CPU if your computer doesn't have one? A white screen normally means it can't initialize the graphics required to draw the user interface. The program should be using OpenGL and be able run on most systems. Even newer systems can sometimes have trouble due to driver issues.

**Comment by ScanMountGoat** [comment]
If you're still experiencing this on the latest version, please make a new issue as the application has changed significantly.
