### ISSUE TITLE
Is the CLI built in to the windows exe?

### ISSUE THREAD

**Issue by Azel-S** [ScanMountGoat/ultimate_tex#8]
I'm trying to use this to create a png from a bntx using command line, but it seems to not care about my arguments at all.

Ex1: ultimate_tex.exe chara_0_koopa_00.bntx result.png
Ex:2 ultimate_tex.exe -- chara_0_koopa_00.bntx result.png
Ex:3 ultimate_tex.exe -p chara_0_koopa_00.bntx result.png

Neither of these work, and all of them just open the GUI. Do I have to build the ultimate_tex_cli from source?

P.S. Thank you for making this, it looks awesome.

**Comment by ScanMountGoat** [comment]
The CLI is called ultimate_tex_cli. You'll need to build it yourself from source for now.

**Comment by Azel-S** [comment]
Question answered, ultimate_tex_cli currently needs to be built from source.
